version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000" # Map container port 5000 to host port 5001
    env_file:
      - .env
    volumes:
      - .:/app
    command: python src/main.py
    restart: always


